version: '3'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /home/svetrie/clickhouse_local:/var/lib/clickhouse
    environment:
      # Must set env vars to connect to ch server programmatically
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
    restart: always
